[project]

name="ecf1"
description="Projeto de refatoração para disciplina de Padrões e Arquitetura de Software"
requires-python = ">=3.11"

authors=[
    {name="Raphael Fernandes de Sellos Moreira"}
]

readme="README.md"

dependencies=[
    "pytest==9.0.3"
]

[tool.pytest.ini_options]
pythonpath = ["."]

# Removendo o codigo legado e main da checkagem do mypy
[tool.mypy]
strict = true
exclude = [
    "src/legacy.py",
    "src/main.py"
]